//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "bank_accounts")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: Uuid,
    pub user_id: i32,
    pub name: String,
    pub account_type: String,
    pub institution: Option<String>,
    pub account_number_last4: Option<String>,
    pub currency: String,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub current_balance: Decimal,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub available_balance: Option<Decimal>,
    pub color: String,
    pub is_active: bool,
    pub last_synced_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id"
    )]
    User,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
    #[sea_orm(has_many = "super::statements::Entity")]
    Statements,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl Related<super::statements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Statements.def()
    }
}
