//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "feature_definitions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub key: String,
    pub name: String,
    pub description: Option<String>,
    pub category: String,
    pub default_enabled: bool,
    pub is_premium: bool,
    pub sort_order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_feature_flags::Entity")]
    UserFeatureFlags,
}

impl Related<super::user_feature_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFeatureFlags.def()
    }
}
