//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "statements")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: Uuid,
    pub user_id: i32,
    pub account_id: Option<i32>,
    pub filename: String,
    pub file_path: String,
    pub file_size: i32,
    pub file_type: String,
    pub status: String,
    pub statement_date: Option<Date>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub transaction_count: i32,
    pub error_message: Option<String>,
    pub processed_at: Option<DateTimeWithTimeZone>,
    pub bank_name: Option<String>,
    pub detection_confidence: Option<i32>,
    pub parser_used: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::bank_accounts::Entity",
        from = "Column::AccountId",
        to = "super::bank_accounts::Column::Id"
    )]
    BankAccount,
    #[sea_orm(has_many = "super::transactions::Entity")]
    Transactions,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::bank_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BankAccount.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}
