//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: Uuid,
    pub user_id: i32,
    pub account_id: i32,
    pub category_id: Option<i32>,
    pub statement_id: Option<i32>,
    pub transaction_date: Date,
    pub posted_date: Option<Date>,
    pub description: String,
    pub original_description: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((19, 4)))")]
    pub amount: Decimal,
    pub transaction_type: String,
    pub status: String,
    pub merchant_name: Option<String>,
    pub reference_number: Option<String>,
    pub notes: Option<String>,
    pub is_recurring: bool,
    pub is_excluded: bool,
    pub transaction_hash: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::bank_accounts::Entity",
        from = "Column::AccountId",
        to = "super::bank_accounts::Column::Id"
    )]
    BankAccount,
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id"
    )]
    Category,
    #[sea_orm(
        belongs_to = "super::statements::Entity",
        from = "Column::StatementId",
        to = "super::statements::Column::Id"
    )]
    Statement,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::bank_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BankAccount.def()
    }
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Category.def()
    }
}

impl Related<super::statements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Statement.def()
    }
}
